### ISSUE TITLE
Problem matcher for `format --check`

### ISSUE THREAD

**Issue by gegoune** [astral-sh/ruff-action#12]
Hi!

Please consider adding [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) such as

```json
{
  "problemMatcher": [
    {
      "owner": "ruff",
      "pattern": [
        {
          "regexp": "^(Would reformat): (.+)$",
          "message": 1,
          "file": 2
        }
      ]
    }
  ]
}
```
so formatting errors can get proper annotations as well.

(Also, I have noticed that `format --check` does not accept `--output-format=github` - is that intentional?)

**Comment by gegoune** [comment]
Issue already exists, it's actually where I got that code from, it seems.
https://github.com/astral-sh/ruff/issues/10430

**Comment by eifinger** [comment]
Thank you for contributing the matcher!
