### ISSUE TITLE
[Bug] PR to update action to v3 causes error, unable to diagnose

### ISSUE THREAD

**Issue by AbstractUmbra** [astral-sh/ruff-action#31]
Hello!

Dependabot [opened a PR](https://github.com/AbstractUmbra/Hondana/pull/48) on my library to update the action as per your new release.

This PR is [currently failing CI](https://github.com/AbstractUmbra/Hondana/actions/runs/12468222270/job/34799619103?pr=48) due to an error output from the action, of which I cannot get to the bottom of due to the output being minimal.

I've attached debug logs from the run to help diagnose the issue.

[logs_32382477606.zip](https://github.com/user-attachments/files/18230471/logs_32382477606.zip)

**Comment by charliermarsh** [comment]
\cc @eifinger in case you have any ideas

**Comment by eifinger** [comment]
> \cc [@eifinger](https://github.com/eifinger) in case you have any ideas

Already debugging this specific pyproject.toml

**Comment by eifinger** [comment]
This is a bug in the toml parsing library we use: https://github.com/BinaryMuse/toml-node/issues/51

I replaced the lib and will release a new version
