### ISSUE TITLE
Publish to GitHub Actions Marketplace

### ISSUE THREAD

**Issue by curtisma** [astral-sh/ruff-action#5]
I was surprised that I couldn't find this action on [the GitHub Actions Marketplace.](https://github.com/marketplace?category=&type=actions&verification=&query=ruff) Once published, it would be the ruff check with the highest number of stars.

You can just follow the GitHub Help instructions on [publishing actions to the marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace).

This was copied from the previous repo:
https://github.com/ChartBoost/ruff-action/issues/12

**Comment by charliermarsh** [comment]
Done: https://github.com/marketplace/actions/ruff-action

**Comment by nitishxp** [comment]
@charliermarsh can you also ensure that the action is verified in the GitHub Marketplace :)
Since our org restrict to use the action that are not verified by github

**Comment by charliermarsh** [comment]
@nitishxp -- I just applied for verification.

**Comment by nitishxp** [comment]
@charliermarsh  thanks , usually how much it takes to get verified?

**Comment by DavidJFelix** [comment]
> @charliermarsh thanks , usually how much it takes to get verified?

https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization#requesting-publisher-verification

Seems like its an unspecified amount of time. From other interactions with github support my guess is about 1 week tops.

**Comment by nitishxp** [comment]
Has action been verified till yet?

**Comment by charliermarsh** [comment]
Yeah a few days ago.

**Comment by charliermarsh** [comment]
![Screenshot 2024-10-14 at 12 30 50 PM](https://github.com/user-attachments/assets/fde95315-6e44-444d-b992-a25e49600ff9)

**Comment by nitishxp** [comment]
Maybe I still not seeing verification badge in gha

**Comment by charliermarsh** [comment]
Apparently the badge showing up in the Marketplace is like a totally separate thing, and you have to email them to get it? https://docs.github.com/en/actions/sharing-automations/creating-actions/publishing-actions-in-github-marketplace#about-badges-in-github-marketplace
