### ISSUE TITLE
Set releases/tags

### ISSUE THREAD

**Issue by tiagovrtr** [astral-sh/ruff-action#6]
Hi @charliermarsh, thanks for supporting this move.
Can we have a new release so we can use this action through a tag?
We could also have the v1.0.0 and v1 release for backwards compatibility (that would be commit e18ae97).

**Comment by charliermarsh** [comment]
Yes will do.

**Comment by charliermarsh** [comment]
Created: https://github.com/astral-sh/ruff-action/releases/tag/v1.0.0
