### ISSUE TITLE
"unable to find version `v1`" when using example from readme

### ISSUE THREAD

**Issue by jimgar** [astral-sh/ruff-action#8]
Hi there

I have a fresh repo. I put the example from the astral-sh/ruff-action readme into my repo's [.github/workflows/ruff.yml](https://github.com/jimgar/ruff-gha-behaviour/blob/7e4bd64a0a7a6e8e814fab2a649392816b08cd19/.github/workflows/ruff.yml)

On push I get the following error when the workflow attempts to run:

```
Error: Unable to resolve action `astral-sh/ruff-action@v1`, unable to find version `v1`
```

Do you think this is simply because the action has only just gone on marketplace, is being verified, something like that? Or something else - possibly that I've done wrong!?

Thank you!

**Comment by jimgar** [comment]
Today I learned: The version needs to come from marketplace, which for latest is `uses: astral-sh/ruff-action@v1.1.0`

Happy to raise a PR that updates `README.md` to reflect this in the examples. Also understand if you prefer to do it yourselves :)

**Comment by DavidJFelix** [comment]
Shoot. I saw that when updating the README and almost corrected it. I was under the impression that github actions had some magic semver that would pick the latest v1 version, but I think this is just a common practice that folks publish a tag for major versions and update it to the latest minor. @charliermarsh do you think we should set up alias tags like `v1` and `v2` that map to the latest minor version in the `v1.x.x` and `v2.x.x` releases, respectively?

**Comment by DavidJFelix** [comment]
![image](https://github.com/user-attachments/assets/d19ef637-aac2-4ac3-9f2d-af6c0571e2b6)
screenshot from chartboost releases page

**Comment by DavidJFelix** [comment]
@jimgar I'm sure a PR would be welcome but this might be something worth fixing in the tag release process for folks who don't want to pin minor versions.

**Comment by jimgar** [comment]
> @jimgar I'm sure a PR would be welcome but this might be something worth fixing in the tag release process for folks who don't want to pin minor versions.

Absolutely, makes sense. Will leave it with you 🙏🏻

**Comment by zanieb** [comment]
Yeah we should have aliases here

**Comment by charliermarsh** [comment]
So there’s supposed to be a v1 tag that’s mutable and constantly updated to point to the latest tagged patch release?

**Comment by zanieb** [comment]
Should be resolved now

**Comment by jimgar** [comment]
Confirmed, thanks so much peeps!
